name: Main Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.12"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up environment variables
      run: |
        echo "DEBUG=True" >> $GITHUB_ENV
        echo "DEVELOPMENT_MODE=True" >> $GITHUB_ENV
        echo "DJANGO_SECRET_KEY=test-secret-key-for-ci" >> $GITHUB_ENV
        
    - name: Check for pending migrations
      run: |
        python manage.py makemigrations --check --dry-run
        
    - name: Apply migrations
      run: |
        python manage.py migrate
        
    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput
        
    - name: Run Django check
      run: |
        python manage.py check
        
    - name: Test server startup
      run: |
        timeout 10s python manage.py runserver 0.0.0.0:8000 &
        sleep 5
        curl -f http://localhost:8000/admin || exit 1
        
    - name: Run tests (if any)
      run: |
        python manage.py test --verbosity=2
      continue-on-error: true 